### PR TITLE
Added option for hiding year and removed some outdated code

### PR DESCRIPTION
**Pull request by TheOneWithTheBraid**
I added a checkbox for hiding the year as described in JugendHackt community before.

Moreover, I removed some outdated code and replaced it with more current APIs.

### CODE REVIEW

**Review by marvinschopf — APPROVED** [review]
Sounds awesome, too! Great idea! Merging now.

**Comment by TheOneWithTheBraid** [comment]
Thanks. Please check the code first. I developed it blindly. :smirk:

**Comment by marvinschopf** [comment]
Yepp, I did. Everything seems to work, only fixing the URL on the builder page. Thank you!

**Comment by TheOneWithTheBraid** [comment]
Fixed blank strings...
Please re-pull from https://github.com/JasMich/Badges-Improved : `noyear`

**Pull request merged**
